name: ci

on:
  push:
    branches:
      - master
  pull_request:

env:
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  centos7-jdk8:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build centos7-jdk8
        run: make centos7-jdk8

      - name: Test centos7-jdk8
        if: "!contains(github.ref, 'refs/heads/master')"
        run: ./scripts/test.sh centos7-jdk8 refs/heads/4.13 "--distribution centos7"

      - name: Login to Docker
        uses: docker/login-action@v1
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push centos7-jdk8
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        run: DOCKER_TAG=centos7-jdk8 make push

  centos7-jdk11:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build centos7-jdk11
        run: make centos7-jdk11

      - name: Test centos7-jdk11
        if: "!contains(github.ref, 'refs/heads/master')"
        run: ./scripts/test.sh centos7-jdk11 refs/heads/4.16 "--distribution centos7"

      - name: Login to Docker
        uses: docker/login-action@v1
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push centos7-jdk11
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        run: DOCKER_TAG=centos7-jdk11 make push

  centos7-jdk11-gcc9-3:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build centos7-jdk11-gcc9.3
        run: make centos7-jdk11-gcc9.3

      - name: Test centos7-jdk11-gcc9.3
        if: "!contains(github.ref, 'refs/heads/master')"
        run: ./scripts/test.sh centos7-jdk11-gcc9.3 refs/heads/4.16 "--distribution centos7"

      - name: Login to Docker
        uses: docker/login-action@v1
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push centos7-jdk11-gcc9.3
        if: contains(github.ref, 'refs/heads/master') && env.REGISTRY_USERNAME != ''
        run: DOCKER_TAG=centos7-jdk11-gcc9.3 make push
